### ISSUE TITLE
Improve Performance

### ISSUE THREAD

**Issue by WalshyDev** [WalshyDev/cf-status-worker#1]
I haven't really worked on the performance of this but currently, it hits a mean of ~48ms. This should definitely be improved.

One way would be to see if we can break the main for loop. 

For anyone who has not worked with Cloudflare Workers before, the official Discord server is a great resource - https://discord.gg/cloudflaredev

**Comment by licitdev** [comment]
I'm working on removing the main `for` loop.

**Comment by WalshyDev** [comment]
v2 took this down from ~25-30ms CPU time to ~10ms.
