### ISSUE TITLE
Tutorial for setup

### ISSUE THREAD

**Issue by WalshyDev** [WalshyDev/cf-status-worker#3]
The README should include a proper tutorial for setting up. Right now it isn't super clear and if the deploy with workers button breaks, there is no easy explanation for those not familiar with Workers.

**Comment by jake-walker** [comment]
I'd like to have a look at this one

**Comment by WalshyDev** [comment]
Sounds good! If you need any help feel free to join the official Cloudflare Workers Discord - https://discord.gg/cloudflaredev
